-- Travel Planner baseline. Kept portable across PostgreSQL and H2 PostgreSQL mode so CI validates
-- the same object names, nullability, foreign keys, checks, unique rules, and access-path indexes.

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    timezone VARCHAR(255) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    default_zoom INTEGER NOT NULL,
    hero_emoji VARCHAR(255),
    CONSTRAINT pk_city PRIMARY KEY (id),
    CONSTRAINT uk_city_name_country UNIQUE (name, country),
    CONSTRAINT ck_city_lat CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT ck_city_lng CHECK (lng BETWEEN -180 AND 180),
    CONSTRAINT ck_city_default_zoom CHECK (default_zoom BETWEEN 1 AND 22)
);

CREATE TABLE poi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    city_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    avg_visit_minutes INTEGER NOT NULL,
    open_hour INTEGER NOT NULL,
    close_hour INTEGER NOT NULL,
    description VARCHAR(400),
    CONSTRAINT pk_poi PRIMARY KEY (id),
    CONSTRAINT fk_poi_city FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE RESTRICT,
    CONSTRAINT ck_poi_lat CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT ck_poi_lng CHECK (lng BETWEEN -180 AND 180),
    CONSTRAINT ck_poi_rating CHECK (rating BETWEEN 0 AND 5),
    CONSTRAINT ck_poi_visit_minutes CHECK (avg_visit_minutes > 0),
    CONSTRAINT ck_poi_open_hour CHECK (open_hour BETWEEN 0 AND 24),
    CONSTRAINT ck_poi_close_hour CHECK (close_hour BETWEEN 0 AND 24),
    CONSTRAINT ck_poi_open_window CHECK (open_hour < close_hour)
);

CREATE TABLE trip (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    city_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    num_days INTEGER NOT NULL,
    day_start_hour INTEGER NOT NULL,
    default_mode VARCHAR(255) NOT NULL,
    CONSTRAINT pk_trip PRIMARY KEY (id),
    CONSTRAINT fk_trip_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT,
    CONSTRAINT fk_trip_city FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE RESTRICT,
    CONSTRAINT ck_trip_num_days CHECK (num_days BETWEEN 1 AND 15),
    CONSTRAINT ck_trip_day_start_hour CHECK (day_start_hour BETWEEN 5 AND 14),
    CONSTRAINT ck_trip_default_mode CHECK (default_mode IN ('WALK', 'TRANSIT', 'DRIVE'))
);

CREATE TABLE itinerary_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trip_id BIGINT NOT NULL,
    poi_id BIGINT NOT NULL,
    day_index INTEGER NOT NULL,
    seq INTEGER NOT NULL,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_itinerary_item PRIMARY KEY (id),
    CONSTRAINT fk_itinerary_item_trip FOREIGN KEY (trip_id) REFERENCES trip (id) ON DELETE CASCADE,
    CONSTRAINT fk_itinerary_item_poi FOREIGN KEY (poi_id) REFERENCES poi (id) ON DELETE RESTRICT,
    CONSTRAINT uk_itinerary_item_trip_poi UNIQUE (trip_id, poi_id),
    CONSTRAINT ck_itinerary_item_day CHECK (day_index >= 1),
    CONSTRAINT ck_itinerary_item_seq CHECK (seq >= 0)
);

-- Foreign keys are not automatically indexed by PostgreSQL. These match repository predicates and
-- sort order; the POI index also supports catalog ranking after city/category filtering.
CREATE INDEX idx_poi_city_category ON poi (city_id, category);
CREATE INDEX idx_poi_city_rating_name ON poi (city_id, rating DESC, name, id);
CREATE INDEX idx_trip_user_id_desc ON trip (user_id, id DESC);
CREATE INDEX idx_trip_city ON trip (city_id);
CREATE INDEX idx_itinerary_trip_day_seq ON itinerary_item (trip_id, day_index, seq);
CREATE INDEX idx_itinerary_poi ON itinerary_item (poi_id);

